openapi: 3.0.0
info:
  title: PlanerAI Weather-TEST API
  description: >-
    testing REST API
  version: 0.0.0
servers:
  - url: http://127.0.0.1:5000/
tags:
  - name: weather

paths:
  /get_weather/{city}:
    get:
      summary: Get weather forecast for a city for the next 5 days
      parameters:
        - name: city
          in: path
          description: Name of the city
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              min_temp:
                type: number
                format: float
                example: 18.5
              max_temp:
                type: number
                format: float
                example: 26.8
              rain_sum:
                type: number
                format: float
                example: 5.7
              wind_speed:
                type: number
                format: float
                example: 12.5
              classification:
                type: string
                example: "rainy"
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
                example: "no city parameter given"
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string
                example: "could not parse weather data"